Repository Fastcampus-Final-Team3/jober-backend, pull requests merged in 2023-09, with the labels that each got.

#9 MemberGroup 엔티티 수정 완료
  src/main/java/com/javajober/entity/MemberGroup.java
Labels: 🐞 BugFix

#13 TemplateAuth 엔티티 수정 완료
  src/main/java/com/javajober/entity/TemplateAuth.java
  src/main/resources/db/temporary.sql
Labels: 🐞 Fix

#18 템플릿 권한 설정 패키지 구조 수정 완료
  src/main/java/com/javajober/template/controller/TemplateBlockController.java
  src/main/java/com/javajober/template/dto/MemberAuthResponse.java
  src/main/java/com/javajober/template/repository/AddSpaceRepository.java
  src/main/java/com/javajober/template/repository/MemberGroupRepository.java
  src/main/java/com/javajober/template/repository/TemplateAuthRepository.java
  src/main/java/com/javajober/template/service/TemplateBlockService.java
Labels: 🔮Chore

#36 에러메시지 수정 완료
  src/main/java/com/javajober/addSpace/repository/AddSpaceRepository.java
  src/main/java/com/javajober/core/message/ErrorMessage.java
  src/main/java/com/javajober/core/message/SuccessMessage.java
  src/main/java/com/javajober/template/repository/AddSpaceRepository.java
  src/main/java/com/javajober/template/repository/MemberGroupRepository.java
  src/main/java/com/javajober/template/repository/SpaceWallCategoryRepository.java
  src/main/java/com/javajober/template/repository/TemplateAuthRepository.java
  src/main/java/com/javajober/template/repository/TemplateRepository.java
  src/main/java/com/javajober/template/service/TemplateBlockService.java
Labels: 🐞 Fix

#40 FCM 토큰 생성 및 저장 로직 구현 완료
  src/main/java/com/javajober/core/fcm/FcmInitializer.java
  src/main/java/com/javajober/core/message/ErrorMessage.java
  src/main/java/com/javajober/entity/AddSpace.java
  src/main/java/com/javajober/entity/MemberGroup.java
  src/main/java/com/javajober/fcm/controller/MemberFcmTokenController.java
  src/main/java/com/javajober/fcm/domain/MemberFcmToken.java
  src/main/java/com/javajober/fcm/dto/MemberFcmTokenRequest.java
  src/main/java/com/javajober/fcm/repository/MemberFcmTokenRepository.java
  src/main/java/com/javajober/fcm/service/MemberFcmTokenService.java
  src/main/java/com/javajober/home/dto/MemberResponse.java
  src/main/java/com/javajober/home/service/HomeService.java
  src/main/java/com/javajober/member/domain/Member.java
  src/main/java/com/javajober/member/repository/MemberRepository.java
Labels: ✨ Feature

#41 깃 충돌을 위한 코드 추가
  src/main/java/com/javajober/core/message/ErrorMessage.java
  src/main/java/com/javajober/template/dto/MemberAuthResponse.java
  src/main/java/com/javajober/template/service/TemplateBlockService.java
Labels: 🐞 Fix

#42 FCM 에러메시지 코드 수정 및 오류 메시지 추가 완료
  src/main/java/com/javajober/core/fcm/FcmInitializer.java
  src/main/java/com/javajober/core/message/ErrorMessage.java
Labels: 🐞 Fix

#46 FCM 토큰 저장 로직 추가 및 개선 완료
  src/main/java/com/javajober/fcm/domain/MemberFcmToken.java
  src/main/java/com/javajober/fcm/repository/MemberFcmTokenRepository.java
  src/main/java/com/javajober/fcm/service/MemberFcmTokenService.java
Labels: ✨ Feature

#55 merge 충돌 해결
  src/main/java/com/javajober/addSpace/repository/AddSpaceRepository.java
  src/main/java/com/javajober/core/message/ErrorMessage.java
  src/main/java/com/javajober/core/message/SuccessMessage.java
  src/main/java/com/javajober/home/dto/MemberResponse.java
  src/main/java/com/javajober/home/service/HomeService.java
  src/main/java/com/javajober/member/repository/MemberRepository.java
Labels: 🐞 Fix

#56 SNS Block CRUD 구현 완료
  src/main/java/com/javajober/entity/SnsType.java
  src/main/java/com/javajober/snsBlock/controller/SNSController.java
  src/main/java/com/javajober/snsBlock/domain/SNSBlock.java
  src/main/java/com/javajober/snsBlock/domain/SNSType.java
  src/main/java/com/javajober/snsBlock/dto/SNSBlockDeleteRequest.java
  src/main/java/com/javajober/snsBlock/dto/SNSBlockRequest.java
  src/main/java/com/javajober/snsBlock/dto/SNSBlockRequests.java
  src/main/java/com/javajober/snsBlock/dto/SNSBlockResponse.java
  src/main/java/com/javajober/snsBlock/dto/SNSBlockResponses.java
  src/main/java/com/javajober/snsBlock/dto/SNSBlockUpdateRequest.java
  src/main/java/com/javajober/snsBlock/repository/SNSBlockRepository.java
  src/main/java/com/javajober/snsBlock/service/SNSBlockService.java
Labels: ✨ Feature, 🐞 Fix

#57 TemplateBlock CRUD 기능 구현
  src/main/java/com/javajober/entity/TemplateAuth.java
  src/main/java/com/javajober/entity/TemplateBlock.java
  src/main/java/com/javajober/template/controller/TemplateBlockController.java
  src/main/java/com/javajober/template/controller/TemplateController.java
  src/main/java/com/javajober/template/dto/TemplateBlockRequest.java
  src/main/java/com/javajober/template/dto/TemplateBlockRequests.java
  src/main/java/com/javajober/template/dto/TemplateBlockResponse.java
  src/main/java/com/javajober/template/repository/MemberGroupRepository.java
  src/main/java/com/javajober/template/repository/TemplateAuthRepository.java
  src/main/java/com/javajober/template/repository/TemplateBlockRepository.java
  src/main/java/com/javajober/template/service/TemplateBlockService.java
  src/main/java/com/javajober/template/service/TemplateService.java
Labels: ✨ Feature

#63 TemplateBlock update 기능 구현
  src/main/java/com/javajober/template/controller/TemplateBlockController.java
  src/main/java/com/javajober/template/domain/TemplateAuth.java
  src/main/java/com/javajober/template/domain/TemplateBlock.java
  src/main/java/com/javajober/template/dto/TemplateBlockUpdateRequest.java
  src/main/java/com/javajober/template/service/TemplateBlockService.java
Labels: ✨ Feature

#72 공유페이지 WallInfoBlock 저장 및 DTO Mapping 기능 구현
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/dto/request/DataRequest.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/wallInfoBlock/domain/WallInfoBlock.java
  src/main/java/com/javajober/wallInfoBlock/dto/request/WallInfoBlockRequest.java
  src/main/java/com/javajober/wallInfoBlock/repository/WallInfoBlockRepository.java
Labels: ✨ Feature

#74 CI/CD오류로 인한 코드 삭제 완료
  .github/workflows/cicd.yml
Labels: 🌏 Deploy

#82 List Block CRUD 기능 구현 및 공유페이지 file block DTO Mapping 기능 구현
  src/main/java/com/javajober/core/message/ErrorMessage.java
  src/main/java/com/javajober/listBlock/domain/ListBlock.java
  src/main/java/com/javajober/listBlock/dto/ListBlockSaveRequest.java
  src/main/java/com/javajober/listBlock/listBlockRepository/ListBlockRepository.java
  src/main/java/com/javajober/spaceWall/domain/BlockType.java
  src/main/java/com/javajober/spaceWall/dto/request/BlockRequest.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#84 SpaceWall 패키지 구조 변경 및 findSpaceWallCategoryTypeByString 기능 구현 완료
  src/main/java/com/javajober/core/message/ErrorMessage.java
  src/main/java/com/javajober/entity/SpaceWallCategoryType.java
  src/main/java/com/javajober/spaceWall/domain/SpaceWall.java
  src/main/java/com/javajober/spaceWall/domain/SpaceWallCategory.java
  src/main/java/com/javajober/spaceWall/domain/SpaceWallCategoryType.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/template/controller/TemplateController.java
  src/main/java/com/javajober/template/domain/Template.java
  src/main/java/com/javajober/template/repository/SpaceWallCategoryRepository.java
  src/main/java/com/javajober/template/service/TemplateService.java
Labels: ✨ Feature, 🔮Chore

#86 SpaceWallService save메소드 switch case문에 break 누락 수정 완료
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔮Chore

#88 임시 저장 API 구현 및 DataRequest dto에 addSpace 추가
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/dto/request/DataRequest.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: ✨ Feature
