Repository Fastcampus-Final-Team3/jober-backend, pull requests merged in 2023-10, with the labels that each got.

#89 개인/단체 스페이스 조회 및 공유페이지 유무 확인 API
  src/main/java/com/javajober/core/message/SuccessMessage.java
  src/main/java/com/javajober/space/controller/SpaceController.java
  src/main/java/com/javajober/space/dto/MemberGroupResponse.java
  src/main/java/com/javajober/space/dto/SpaceResponse.java
  src/main/java/com/javajober/space/repository/MemberGroupRepository.java
  src/main/java/com/javajober/space/repository/SpaceWallRepository.java
  src/main/java/com/javajober/space/service/SpaceService.java
Labels: ✨ Feature

#91 space 패키지 구조 변경 및 repository 삭제
  src/main/java/com/javajober/space/repository/MemberGroupRepository.java
  src/main/java/com/javajober/space/repository/SpaceWallRepository.java
  src/main/java/com/javajober/space/service/SpaceService.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/template/repository/MemberGroupRepository.java
Labels: 🐞 Fix

#93 spaceWall 테이블에 json으로 저장 구현완료
  src/main/java/com/javajober/fileBlock/repository/FileBlockRepository.java
  src/main/java/com/javajober/freeBlock/repository/FreeBlockRepository.java
  src/main/java/com/javajober/spaceWall/domain/SpaceWall.java
  src/main/java/com/javajober/spaceWall/dto/request/SpaceWallRequest.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: ✨ Feature

#94 saveTemplateBlocks 메서드 권한설정 로직 삭제
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔨 Refactor

#96 saveTemplateBlocks 메서드 권한설정 로직 삭제 완료
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: ✨ Feature, 🐞 Fix

#102 Template 카테고리 추천 enum으로 변경
  src/main/java/com/javajober/template/service/TemplateService.java
  src/main/java/com/javajober/templateBlock/repository/TemplateRepository.java
Labels: 🔮Chore

#103 템플릿 패키지 구조 변경
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/template/controller/TemplateController.java
  src/main/java/com/javajober/template/domain/Template.java
  src/main/java/com/javajober/template/domain/TemplateAuth.java
  src/main/java/com/javajober/template/dto/response/TemplateResponse.java
  src/main/java/com/javajober/template/repository/TemplateAuthRepository.java
  src/main/java/com/javajober/template/repository/TemplateRepository.java
  src/main/java/com/javajober/template/service/TemplateService.java
  src/main/java/com/javajober/templateBlock/controller/TemplateBlockController.java
  src/main/java/com/javajober/templateBlock/domain/TemplateBlock.java
  src/main/java/com/javajober/templateBlock/dto/request/TemplateBlockDeleteRequest.java
  src/main/java/com/javajober/templateBlock/dto/request/TemplateBlockRequest.java
  src/main/java/com/javajober/templateBlock/dto/request/TemplateBlockRequests.java
  src/main/java/com/javajober/templateBlock/dto/request/TemplateBlockUpdateRequest.java
  src/main/java/com/javajober/templateBlock/dto/response/TemplateBlockResponse.java
  src/main/java/com/javajober/templateBlock/dto/response/TemplateBlockResponses.java
  src/main/java/com/javajober/templateBlock/repository/TemplateBlockRepository.java
  src/main/java/com/javajober/templateBlock/service/TemplateBlockService.java
Labels: 🔮Chore

#104 템플릿 카테고리 별 조회 수정
  src/main/java/com/javajober/template/repository/TemplateRepository.java
  src/main/java/com/javajober/template/service/TemplateService.java
Labels: 🔮Chore

#112 공유페이지 update 기능 구현
  src/main/java/com/javajober/fileBlock/dto/request/FileBlockUpdateRequest.java
  src/main/java/com/javajober/fileBlock/service/FileBlockService.java
  src/main/java/com/javajober/listBlock/domain/ListBlock.java
  src/main/java/com/javajober/listBlock/dto/request/ListBlockUpdateRequest.java
  src/main/java/com/javajober/listBlock/repository/ListBlockRepository.java
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/domain/SpaceWall.java
  src/main/java/com/javajober/spaceWall/dto/request/DataUpdateRequest.java
  src/main/java/com/javajober/spaceWall/dto/request/SpaceWallUpdateRequest.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/templateBlock/service/TemplateBlockService.java
  src/main/java/com/javajober/wallInfoBlock/domain/WallInfoBlock.java
  src/main/java/com/javajober/wallInfoBlock/dto/request/WallInfoBlockUpdateRequest.java
  src/main/java/com/javajober/wallInfoBlock/repository/WallInfoBlockRepository.java
Labels: ✨ Feature

#117 공유페이지 저장, 임시저장 응답 데이터 변경 완료
  src/main/java/com/javajober/core/message/SuccessMessage.java
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/dto/response/SpaceWallSaveResponse.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔨 Refactor

#122 공유페이지 space_wall 테이블에 업데이트 되도록 수정
  src/main/java/com/javajober/spaceWall/domain/SpaceWall.java
  src/main/java/com/javajober/spaceWall/dto/request/DataUpdateRequest.java
  src/main/java/com/javajober/spaceWall/dto/request/SpaceWallUpdateRequest.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔨 Refactor

#128 배포 후 오류로 인한 SpaceWall 조회 로직 수정 완료
  src/main/java/com/javajober/space/service/SpaceService.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
Labels: 🐞 Fix

#133 fileBlock 엔티티에 file 컬럼 추가 완료
  src/main/java/com/javajober/fileBlock/domain/FileBlock.java
  src/main/java/com/javajober/fileBlock/dto/request/FileBlockStringRequest.java
  src/main/java/com/javajober/fileBlock/dto/request/FileBlockStringUpdateRequest.java
  src/main/java/com/javajober/fileBlock/dto/request/FileBlockUpdateRequest.java
Labels: 🔨 Refactor

#135 FileBlock 패키지 구조 변경
  src/main/java/com/javajober/fileBlock/controller/FileBlockController.java
  src/main/java/com/javajober/fileBlock/filedto/FileBlockSaveRequest.java
  src/main/java/com/javajober/fileBlock/filedto/FileBlockSaveRequests.java
  src/main/java/com/javajober/fileBlock/filedto/FileBlockUpdateRequest.java
  src/main/java/com/javajober/fileBlock/filedto/FileBlockUpdateRequests.java
  src/main/java/com/javajober/fileBlock/service/FileBlockService.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔮Chore

#136 file추가로 인한 FileBlock 수정
  src/main/java/com/javajober/fileBlock/domain/FileBlock.java
  src/main/java/com/javajober/fileBlock/service/FileBlockService.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔮Chore

#138 FileBlockResponse file 필드 추가 완료
  src/main/java/com/javajober/fileBlock/dto/response/FileBlockResponse.java
Labels: 🔨 Refactor

#141 홈 API 데이터 addSpaceId -> spaceId로 수정완료
  src/main/java/com/javajober/home/dto/response/AddSpaceResponse.java
Labels: 🔨 Refactor

#144 공유페이지 url 중복 검사 기능 구현 완료
  src/main/java/com/javajober/core/message/SuccessMessage.java
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/dto/response/DuplicateURLResponse.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
Labels: ✨ Feature

#147 StyleSettingBlockId 추가 완료
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
  src/main/java/com/javajober/styleSetting/dto/response/StyleSettingResponse.java
Labels: 🔮Chore

#150 임시 저장 공간 완전 삭제 로직으로 변경 완료
  src/main/java/com/javajober/spaceWall/domain/SpaceWall.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
Labels: 🔮Chore

#152 공유페이지 임시 저장 유무 확인 로직 수정 완료
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
Labels: 🔮Chore

#154 Exception Handler & API 응답 클래스 리팩토링 완료
  src/main/java/com/javajober/core/error/GlobalExceptionHandler.java
  src/main/java/com/javajober/core/util/ApiResponse.java
  src/main/java/com/javajober/exception/ApiStatus.java
  src/main/java/com/javajober/exception/ApplicationException.java
  src/main/java/com/javajober/exception/ApplicationExceptionHandler.java
Labels: 🔨 Refactor

#156 Home 리팩토링 완료
  src/main/java/com/javajober/home/controller/HomeController.java
  src/main/java/com/javajober/home/service/HomeService.java
  src/main/java/com/javajober/member/repository/MemberRepository.java
  src/main/java/com/javajober/space/repository/AddSpaceRepository.java
Labels: 🔨 Refactor

#157 GitHub Actions 활용한 CI / CD 프로세스 구축
  .github/workflows/cicd.yml
  src/main/resources/application.yml
Labels: ✨ Feature, 🌏 Deploy

#159 공유페이지 생성 (임시 저장 유무) API 리팩토링 완료
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
Labels: 🔨 Refactor

#161 개인/단체 스페이스 API 리팩토링 완료
  src/main/java/com/javajober/exception/ApplicationExceptionHandler.java
  src/main/java/com/javajober/memberGroup/repository/MemberGroupRepository.java
  src/main/java/com/javajober/space/controller/SpaceController.java
  src/main/java/com/javajober/space/dto/response/MemberGroupResponse.java
  src/main/java/com/javajober/space/dto/response/SpaceResponse.java
  src/main/java/com/javajober/space/repository/AddSpaceRepository.java
  src/main/java/com/javajober/space/service/SpaceService.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
Labels: 🔨 Refactor

#167 회원가입, 로그인, 로그아웃, 토큰 재발급 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/javajober/member/controller/MemberController.java
  src/main/java/com/javajober/member/domain/Member.java
  src/main/java/com/javajober/member/dto/MemberLoginRequest.java
  src/main/java/com/javajober/member/dto/MemberLoginResponse.java
  src/main/java/com/javajober/member/dto/MemberSignupRequest.java
  src/main/java/com/javajober/member/dto/MemberSignupResponse.java
  src/main/java/com/javajober/member/repository/MemberRepository.java
  src/main/java/com/javajober/member/service/MemberService.java
  src/main/java/com/javajober/refreshToken/domain/RefreshToken.java
  src/main/java/com/javajober/refreshToken/dto/RefreshTokenRequest.java
  src/main/java/com/javajober/refreshToken/repository/RefreshTokenRepository.java
  src/main/java/com/javajober/refreshToken/service/RefreshTokenService.java
  src/main/java/com/javajober/security/AuthenticationManagerConfig.java
  src/main/java/com/javajober/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/javajober/security/JwtAuthenticationFilter.java
  src/main/java/com/javajober/security/JwtAuthenticationProvider.java
  src/main/java/com/javajober/security/JwtAuthenticationToken.java
  src/main/java/com/javajober/security/JwtExceptionCode.java
  src/main/java/com/javajober/security/JwtTokenizer.java
  src/main/java/com/javajober/security/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#168 스페이스 생성 API 기능 구현 완료
  src/main/java/com/javajober/exception/ApplicationExceptionHandler.java
  src/main/java/com/javajober/fileBlock/domain/FileBlock.java
  src/main/java/com/javajober/space/controller/SpaceController.java
  src/main/java/com/javajober/space/domain/AddSpace.java
  src/main/java/com/javajober/space/domain/SpaceType.java
  src/main/java/com/javajober/space/dto/request/SpaceSaveRequest.java
  src/main/java/com/javajober/space/dto/response/SpaceSaveResponse.java
  src/main/java/com/javajober/space/repository/AddSpaceRepository.java
  src/main/java/com/javajober/space/service/SpaceService.java
  src/main/resources/db/temporary.sql
Labels: ✨ Feature, 🔮Chore

#169 예외처리 및 시큐리티 config 수정
  src/main/java/com/javajober/exception/ApplicationExceptionHandler.java
  src/main/java/com/javajober/member/controller/MemberController.java
  src/main/java/com/javajober/member/service/MemberService.java
  src/main/java/com/javajober/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🔮Chore

#171 공유페이지 url로 조회 API 리팩토링 완료
  src/main/java/com/javajober/member/controller/MemberController.java
  src/main/java/com/javajober/security/SecurityConfig.java
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/resources/db/temporary.sql
Labels: 🔨 Refactor, 🔮Chore

#172 시큐리티 config 수정
  src/main/java/com/javajober/security/SecurityConfig.java
Labels: 🔮Chore

#180 공유페이지 저장 API 리팩토링
  src/main/java/com/javajober/blocks/styleSetting/backgroundSetting/dto/request/BackgroundSettingStringSaveRequest.java
  src/main/java/com/javajober/blocks/styleSetting/backgroundSetting/filedto/BackgroundSettingSaveRequest.java
  src/main/java/com/javajober/blocks/styleSetting/blockSetting/dto/request/BlockSettingSaveRequest.java
  src/main/java/com/javajober/blocks/styleSetting/blockSetting/service/BlockSettingService.java
  src/main/java/com/javajober/blocks/styleSetting/dto/request/StyleSettingStringSaveRequest.java
  src/main/java/com/javajober/blocks/styleSetting/themeSetting/dto/request/ThemeSettingSaveRequest.java
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/domain/BlockType.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/spaceWall/strategy/BlockJsonProcessor.java
  src/main/java/com/javajober/spaceWall/strategy/BlockStrategyFactory.java
  src/main/java/com/javajober/spaceWall/strategy/BlockStrategyName.java
  src/main/java/com/javajober/spaceWall/strategy/FixBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/MoveBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/StyleSettingBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/WallInfoBlockStrategy.java
Labels: 🔨 Refactor

#182 공유페이지 (완성/임시저장) 조회 API 리팩토링 완료
  src/main/java/com/javajober/blocks/styleSetting/backgroundSetting/dto/response/BackgroundSettingResponse.java
  src/main/java/com/javajober/blocks/styleSetting/blockSetting/dto/response/BlockSettingResponse.java
  src/main/java/com/javajober/blocks/styleSetting/dto/response/StyleSettingResponse.java
  src/main/java/com/javajober/blocks/styleSetting/themeSetting/dto/response/ThemeSettingResponse.java
  src/main/java/com/javajober/blocks/wallInfoBlock/dto/response/WallInfoBlockResponse.java
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/domain/BlockType.java
  src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
  src/main/java/com/javajober/spaceWall/strategy/BlockJsonProcessor.java
  src/main/java/com/javajober/spaceWall/strategy/BlockStrategyFactory.java
  src/main/java/com/javajober/spaceWall/strategy/BlockStrategyName.java
  src/main/java/com/javajober/spaceWall/strategy/FixBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/MoveBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/StyleSettingStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/WallInfoBlockStrategy.java
Labels: 🔨 Refactor

#184 yml 파일 수정 및 회원가입 중복 방지 로직 추가
  src/main/java/com/javajober/member/repository/MemberRepository.java
  src/main/java/com/javajober/member/service/MemberService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🔮Chore

#185 토큰 만료시간 수정
  src/main/java/com/javajober/core/security/JwtTokenizer.java
Labels: 🔮Chore

#187 멀티파트 파일 용량 설정 및 코드 정리 완료
  src/main/java/com/javajober/core/config/FileDirectoryConfig.java
  src/main/java/com/javajober/core/exception/ApiStatus.java
  src/main/java/com/javajober/core/exception/ApplicationExceptionHandler.java
  src/main/java/com/javajober/core/util/file/FileImageService.java
  src/main/java/com/javajober/space/domain/SpaceType.java
  src/main/java/com/javajober/space/service/SpaceService.java
  src/main/java/com/javajober/spaceWall/controller/FileUploadController.java
  src/main/java/com/javajober/spaceWall/dto/request/BlockSaveRequest.java
  src/main/java/com/javajober/spaceWall/dto/request/DataStringSaveRequest.java
  src/main/java/com/javajober/spaceWall/dto/request/DataStringUpdateRequest.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
  src/main/java/com/javajober/spaceWall/strategy/BlockJsonProcessor.java
  src/main/resources/application-prod.yml
Labels: 🔨 Refactor

#188 공유페이지 저장/임시저장 API 리팩토링 완료
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/dto/request/BlockSaveRequest.java
  src/main/java/com/javajober/spaceWall/dto/request/DataStringSaveRequest.java
  src/main/java/com/javajober/spaceWall/dto/request/DataStringUpdateRequest.java
  src/main/java/com/javajober/spaceWall/filedto/DataSaveRequest.java
  src/main/java/com/javajober/spaceWall/filedto/DataUpdateRequest.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/spaceWall/strategy/BlockJsonProcessor.java
  src/main/java/com/javajober/spaceWall/strategy/BlockStrategyFactory.java
  src/main/java/com/javajober/spaceWall/strategy/BlockStrategyName.java
  src/main/java/com/javajober/spaceWall/strategy/FixBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/MoveBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/StyleSettingStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/WallInfoBlockStrategy.java
Labels: 🔨 Refactor

#189 Template 리팩토링
  src/main/java/com/javajober/template/controller/TemplateController.java
Labels: 🔮Chore

#191 여러 BlockStrategy의 saveBlocks 메서드 리팩토링
  src/main/java/com/javajober/blocks/fileBlock/repository/FileBlockRepository.java
  src/main/java/com/javajober/blocks/freeBlock/repository/FreeBlockRepository.java
  src/main/java/com/javajober/blocks/listBlock/repository/ListBlockRepository.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
Labels: 🔨 Refactor

#193 회원 가입 시 스페이스 생성 기능 구현 완료
  src/main/java/com/javajober/member/service/MemberService.java
  src/main/java/com/javajober/space/dto/request/SpaceSaveRequest.java
  src/main/java/com/javajober/space/repository/AddSpaceRepository.java
Labels: ✨ Feature

#195 여러 BlockStrategy의 saveBlocks 메서드 매개변수 변경 및 blockUUID 추출 방식 수정 완료
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/spaceWall/strategy/BlockJsonProcessor.java
  src/main/java/com/javajober/spaceWall/strategy/MoveBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/StyleSettingStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/WallInfoBlockStrategy.java
Labels: 🔨 Refactor

#197 ResponseEntity 반환 형식을 ApiResponse로 변경 및 회원 아이디 추출 및 SpaceWallService 매개변수 수정 완료
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/dto/request/DataStringUpdateRequest.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔨 Refactor

#199 공유페이지 조회 시 blockType enum으로 수정 완료
  src/main/java/com/javajober/spaceWall/controller/FileUploadController.java
  src/main/java/com/javajober/spaceWall/filedto/DataSaveRequest.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
Labels: 🔨 Refactor

#202 SpaceWallTemporaryService의 delete 메서드를 EntityManager를 활용하여 리팩토링 완료
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallTemporaryService.java
Labels: 🐞 Fix, 🔨 Refactor

#203 공유페이지 멀티파트 파일 처리를 위한 저장 리팩토링
  src/main/java/com/javajober/core/exception/ApiStatus.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/spaceWall/strategy/FixBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/MoveBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/StyleSettingStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/WallInfoBlockStrategy.java
Labels: 🔨 Refactor

#205 공유페이지 외부 공개 api 기능 구현 및 리팩토링 완료
  src/main/java/com/javajober/core/exception/ApiStatus.java
  src/main/java/com/javajober/core/security/SecurityConfig.java
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/domain/SpaceWall.java
  src/main/java/com/javajober/spaceWall/dto/request/IsPublicUpdateRequest.java
  src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: ✨ Feature, 🔨 Refactor

#207 공유페이지 조회 시 spaceId -> spaceWallId로 수정
  src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
Labels: 🔮Chore

#209 shareURL 중복 검사 API 리팩토링 및 저장 예외 처리 로직 추가 완료
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🔨 Refactor

#213 공유페이지 url로 조회 api 수정 완료
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
Labels: 🐞 Fix

#215 공유페이지 수정 API 리팩토링
  src/main/java/com/javajober/blocks/fileBlock/repository/FileBlockRepository.java
  src/main/java/com/javajober/blocks/freeBlock/repository/FreeBlockRepository.java
  src/main/java/com/javajober/blocks/listBlock/repository/ListBlockRepository.java
  src/main/java/com/javajober/blocks/snsBlock/dto/request/SNSBlockUpdateRequest.java
  src/main/java/com/javajober/blocks/snsBlock/repository/SNSBlockRepository.java
  src/main/java/com/javajober/blocks/styleSetting/backgroundSetting/domain/BackgroundSetting.java
  src/main/java/com/javajober/blocks/styleSetting/domain/StyleSetting.java
  src/main/java/com/javajober/blocks/styleSetting/themeSetting/domain/ThemeSetting.java
  src/main/java/com/javajober/blocks/templateBlock/domain/TemplateBlock.java
  src/main/java/com/javajober/blocks/templateBlock/dto/request/TemplateBlockUpdateRequest.java
  src/main/java/com/javajober/blocks/templateBlock/repository/TemplateBlockRepository.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/spaceWall/strategy/BlockJsonProcessor.java
  src/main/java/com/javajober/spaceWall/strategy/FixBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/MoveBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/StyleSettingStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/WallInfoBlockStrategy.java
Labels: 🔨 Refactor

#217 홈 조회 API에 JWT 토큰 기반 인증으로 변경 및 응답 엔드포인트 수정 완료
  src/main/java/com/javajober/home/controller/HomeController.java
  src/main/java/com/javajober/home/dto/response/HomeResponse.java
  src/main/java/com/javajober/home/dto/response/MemberResponse.java
  src/main/java/com/javajober/member/repository/MemberRepository.java
  src/main/java/com/javajober/space/repository/AddSpaceRepository.java
Labels: 🔨 Refactor

#219 공유페이지 응답DTO에 memberId 추가 완료
  src/main/java/com/javajober/spaceWall/controller/SpaceWallController.java
  src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
Labels: 🔮Chore

#221 validateAddSpaceId와 checkDuplicateShareURL 메서드에 FlagType 매개변수 추가 완료
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
Labels: 🐞 Fix, 🔨 Refactor

#223 공유페이지 멀티파트 파일 처리를 위한 수정 리팩토링 완료
  src/main/java/com/javajober/blocks/fileBlock/domain/FileBlock.java
  src/main/java/com/javajober/blocks/fileBlock/filedto/FileBlockUpdateRequest.java
  src/main/java/com/javajober/blocks/styleSetting/backgroundSetting/domain/BackgroundSetting.java
  src/main/java/com/javajober/spaceWall/dto/request/SpaceWallStringUpdateRequest.java
  src/main/java/com/javajober/spaceWall/service/FileUploadService.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallService.java
  src/main/java/com/javajober/spaceWall/strategy/FixBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/MoveBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FileBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/FreeBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/ListBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/SNSBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/StyleSettingStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/TemplateBlockStrategy.java
  src/main/java/com/javajober/spaceWall/strategy/impl/WallInfoBlockStrategy.java
Labels: 🔨 Refactor

#224 공유페이지 url로 조회 시 FlagType이 SAVED인 페이지만 조회되도록 수정 완료
  src/main/java/com/javajober/spaceWall/repository/SpaceWallRepository.java
Labels: 🐞 Fix

#225 SpaceWallResponse에 spaceId 추가 완료
  src/main/java/com/javajober/spaceWall/dto/response/SpaceWallResponse.java
  src/main/java/com/javajober/spaceWall/service/SpaceWallFindService.java
Labels: 🔮Chore
